---
- name: Install Apache Server
  hosts: web3
  become: yes

  tasks:
  - block: #Ubuntu
    - name: Install Apache
      apt: name=apache2 state=latest

    - name: Start and enable Apache
      service: name=apache2 state=started enabled=yes
    when: ansible_os_family == "Debian"

  - block: #CentOS
    - name: Install Apache
#      ansible.builtin.yum:
#      name: wget
#      state: latest
#      yum: name=apache2 state=latest
#      dnf: name=wget state=present
      command: yum install httpd -y
#       shell: yum install httpd -y

    - name: Start and enable Apache
      service: name=httpd state=started enabled=yes
    when: ansible_os_family == "RedHat"
