---
- name: Configure IPTables
  hosts: srv-web
  become: true
  tasks:
  - block:

    - name: Drop Invalid Connections
      iptables:
        chain: INPUT
        ctstate: INVALID
        jump: DROP

    - name: Allow Related and Established Connections
      ansible.builtin.iptables:
        chain: INPUT
        ctstate: RELATED,ESTABLISHED
        jump: ACCEPT
        state: present

    - name: Allow port 443 (HTTPS)
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 443
        jump: ACCEPT
        comment: Accept HTTPS connections.

    - name: Allow port 22 (SSH)
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 22
        jump: ACCEPT
        comment: Accept SSH connections.

  handlers:
    - name: Save IPTables
      ansible.builtin.command:
        cmd: iptables-save --file /etc/iptables/rules.v4
