---
- name: Create OAS users
  user:
    name: "{{ item.username }}"
    password: "{{ plain_text_password | password_hash('sha512') }}"
    shell: /bin/bash
    createhome: yes
    groups: sudo
  with_items: "{{ users }}"
