---
- name: Delete user
  hosts: Delete_User
  become: yes

#  vars:
#    username: android

  tasks:
  - name: Delete user {{ username  }}
    user:
     name: '{{ username  }}'
     state: absent
     remove: yes
