---
- name: Install Package
  hosts: srv-web
  become: yes

#  vars:
#    package_debian_name: apache2
#    package_redhat_name: httpd

  tasks:
  - block: #Debian
    - name: Install Debian Package
      apt: name={{ package_debian_name }} state=latest
    when: ansible_os_family == "Debian"

  - block: #RedHat
    - name: Install RedHat Package
      command: yum install {{ package_redhat_name }} -y
    when: ansible_os_family == "RedHat"
