---
- name: Install ssh keys
  hosts: web_servers
  become: yes

  vars_files:
    - /etc/ansible/oas_users.yml

  tasks:

  - name: Create .ssh directory, if it doesn't exist
    file:
      path: "/home/{{ item.username }}/.ssh"
      state: directory
      mode: '0700'
      owner: "{{ item.username }}"
      group: "{{ item.username }}"
    with_items: "{{ users }}"

  - name: Install keys
    authorized_key:
      user: "{{ item.username }}"
      state: "{{ item.state }}"
      key: "{{ lookup('file', item.keyfile ) }}"
    with_items: "{{ users }}"

  - name: Make correct rights for authorized_keys
    file:
      path: "/home/{{ item.username }}/.ssh/authorized_keys"
      state: file
      mode: '0600'
      owner: "{{ item.username }}"
      group: "{{ item.username }}"
    with_items: "{{ users }}"
